FROM mcr.microsoft.com/devcontainers/base:jammy


RUN apt-get update && \
    apt-get -y install build-essential && \
    apt-get -y install flex-old && \
    apt-get -y install bison && \
    apt-get -y install gdb